/*
 * Copyright [2015] [Charles Joseph Staal]
 */
package com.staalcomputingsolutions.snserver.view.gui.clientlisting;

/**
 *
 * @author Charles Joseph Staal
 */
public class CommercialListing extends javax.swing.JPanel {

    /**
     * Creates new form clientListing
     */
    public CommercialListing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelType = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        labelBusinessName = new javax.swing.JLabel();
        businessNameLabel = new javax.swing.JLabel();
        labelPhone = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        labelOnline = new javax.swing.JLabel();
        onlineLabel = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        labelIPAddress = new javax.swing.JLabel();
        ipAddressLabel = new javax.swing.JLabel();
        labelPort = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        labelOwnerName = new javax.swing.JLabel();
        ownerNameLabel = new javax.swing.JLabel();

        labelType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelType.setText("Type:");

        typeLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        typeLabel.setText("Commercial");

        labelBusinessName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelBusinessName.setText("Business name:");

        businessNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        businessNameLabel.setText("jLabel1");

        labelPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPhone.setText("Phone number:");

        phoneNumberLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneNumberLabel.setText("jLabel1");

        labelAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAddress.setText("Address:");

        addressLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addressLabel.setText("jLabel2");

        labelOnline.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelOnline.setText("Online:");

        onlineLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        onlineLabel.setText("jLabel1");

        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelStatus.setText("STATUS:");

        statusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        statusLabel.setText("jLabel2");

        labelIPAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelIPAddress.setText("IP Address:");

        ipAddressLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ipAddressLabel.setText("jLabel4");

        labelPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPort.setText("Port:");

        portLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        portLabel.setText("jLabel1");

        labelOwnerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelOwnerName.setText("Owner name:");

        ownerNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ownerNameLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOwnerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ownerNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(labelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(labelIPAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipAddressLabel)
                        .addGap(18, 18, 18)
                        .addComponent(labelPort))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(labelBusinessName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(businessNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(labelPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumberLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOnline)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onlineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(labelStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(portLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(labelBusinessName)
                    .addComponent(businessNameLabel)
                    .addComponent(labelPhone)
                    .addComponent(phoneNumberLabel)
                    .addComponent(labelOnline)
                    .addComponent(onlineLabel)
                    .addComponent(labelStatus)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(addressLabel)
                    .addComponent(labelIPAddress)
                    .addComponent(ipAddressLabel)
                    .addComponent(labelPort)
                    .addComponent(portLabel)
                    .addComponent(labelOwnerName)
                    .addComponent(ownerNameLabel))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel businessNameLabel;
    private javax.swing.JLabel ipAddressLabel;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBusinessName;
    private javax.swing.JLabel labelIPAddress;
    private javax.swing.JLabel labelOnline;
    private javax.swing.JLabel labelOwnerName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPort;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel onlineLabel;
    private javax.swing.JLabel ownerNameLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
